### ISSUE TITLE
How can I set it up for 1920x1080

### ISSUE THREAD

**Issue by syylvette** [NeshHari/XMonad#4]
The poylbar seems to go out of my screen in my laptop
Also the widgets are not alligned

**Comment by NeshHari** [comment]
For polybar, you can modify the width and offset-x in ~/.config/polybar/Ewwification/config.ini till it fits your configuration. For eww widgets, simply change the (x: ) value for each defwindow till its aligned (~/.config/eww/eww.yuck). Then simply restart xmonad with mod+q which should automatically kill and reopen all polybar and eww modules. This is an expected issue since there is no one-size-fits-all approach.

**Comment by syylvette** [comment]
Thanks will try it

**Comment by NeshHari** [comment]
No problem. I've updated `eww.yuck` to use _percentages_ rather than _px_ on the x-axis. May not be a perfect fit but all elements should now be visible on screen :)
