### ISSUE TITLE
nerd-fonts-sarasa-mono currently not working not maintained

### ISSUE THREAD

**Issue by nrthIxne** [NeshHari/XMonad#6]
Hi,

I am so sorry to open another issue. I tried the new version of the `setup.sh` script during the weekend and everything went fine, except for installing nerd-fonts-sarasa-mono. 
Checking the package page (https://aur.archlinux.org/packages/nerd-fonts-sarasa-mono) it looks like the package might have no maintainer atm.
Trying to install the package through the AUR results in:
`curl: (22) The requested URL returned error: 404`

Just as a heads-up. Thanks again for all the work! You can close the issue if you'd like.

**Comment by NeshHari** [comment]
Yet another issue with nerd fonts on the AUR. I'll switch it up when I find a suitable alternative. Thank you!

**Comment by NeshHari** [comment]
Switched from sarasa mono nerd to regular fira code (not nerd) from the official repos since it only affects the notification content body. I think its reasonable to assume ligatures/icons won't be needed for the body text itself. These nerd fonts are driving me nuts! Anyways thank you mate I truly appreciate it :)

**Comment by nrthIxne** [comment]
Awesome, I will give it a try when I find the time to do so! Thank you for all your work!
